enum PitchIntelligence {
  HUMAN = "HUMAN",
  ARTIFICIAL = "ARTIFICIAL",
}

enum PitchBidValidation {
  VALID = "VALID",
  LESS_THAN_2 = "LESS_THAN_2",
  NOT_EXCEED_BID = "NOT_EXCEED_BID",
  EXCEED_4 = "EXCEED_4",
  EXCEED_5 = "EXCEED_5",
  NO_BID = "NO_BID",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
}

enum PitchPlayValidation {
  VALID = "VALID",
  NOT_FOLLOWING_SUIT = "NOT_FOLLOWING_SUIT",
  NOT_IN_HAND = "NOT_IN_HAND",
  INVALID_CARD = "INVALID_CARD",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
}

enum PitchErrorKey {
  PITCH_501 = "PITCH_501",
  OPTIONS_400 = "OPTIONS_400",
  BIDDER_404 = "BIDDER_404",
  STATE_500_NO_TRUMP = "STATE_500_NO_TRUMP",
  STATE_500_NO_TRICK_WINNER = "STATE_500_NO_TRICK_WINNER",
  STATE_404_TEAM = "STATE_404_TEAM",
  STATE_404_BIDDER = "STATE_404_BIDDER",
  CALC_500_EXTRA_JACK = "CALC_500_EXTRA_JACK",
  BID_400_LESS_THAN_2 = "BID_400_LESS_THAN_2",
  BID_400_NOT_EXCEED_BID = "BID_400_NOT_EXCEED_BID",
  BID_400_EXCEED_4 = "BID_400_EXCEED_4",
  BID_400_EXCEED_5 = "BID_400_EXCEED_5",
  BID_400_NO_BID = "BID_400_NO_BID",
  BID_400_TOO_MANY_ATTEMPTS = "BID_400_TOO_MANY_ATTEMPTS",
  PLAY_400_NOT_FOLLOWING_SUIT = "PLAY_400_NOT_FOLLOWING_SUIT",
  PLAY_400_NOT_IN_HAND = "PLAY_400_NOT_IN_HAND",
  PLAY_400_INVALID_CARD = "PLAY_400_INVALID_CARD",
  PLAY_400_TOO_MANY_ATTEMPTS = "PLAY_400_TOO_MANY_ATTEMPTS",
  TRICK_500_NO_WINNER = "TRICK_500_NO_WINNER",
}

export {
  PitchIntelligence,
  PitchBidValidation,
  PitchPlayValidation,
  PitchErrorKey,
};
